### ISSUE TITLE
Depending on locally defined packages

### ISSUE THREAD

**Issue by Bobbbay** [claymager/idris2-pkgs#9]
Since `buildIdris` is now exposed to consumer flakes, it must be possible to add custom packages to a project (via an overlay (?)), that are then callable in a TOML file. To be completely honest, I'm not exactly certain the steps to do so, but here's exactly what I'd like to do:

```toml
# myproject/other-packages/some-package.toml
name = "some-package"
[ source ]
# etc...
```

```toml
# myproject/myproject.toml
[ depends ]
idrisLibs = [ "some-package" ]
```

```nix
# myproject/flake.nix
# ???
```

Am I overthinking this?

**Comment by Bobbbay** [comment]
On a relatively different vein, I just noticed that an `idrisPackages` set exists on nixpkgs, which contains (one of) the packages I want to depend on (`effects`). However, it doesn't work when I add it to my TOML `depends.idrisLibs`. Why doesn't `idris2-pkgs` channel from these derivations as well?

**Comment by Bobbbay** [comment]
I have figured out to use `callNix` on an attrset containing the package. I cannot used callTOML because, well, it's not exposed :). So... I'm stuck on two points:

 * Should we expose callTOML so that I can write local packages in TOML instead of Nix?
 * How do I add my new, local package to the list of packages that `idris2-pkgs` reads in `idrisLibs`? i.e., the following doesn't work:

```toml
# myproject/myproject.toml
[ depends ]
idrisLibs = [ "some-package" ] # err: some-package doesn't exist
```

I have tried adding `some-package` to my `pkgs.idrisPackages` via an overlay, but that doesn't help the situation. Thoughts?
